
# Build settings
remote_theme: zeyu-xie/Lavender-Scholar-Lite
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Basic Site Info

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zeyu-xie.github.io/Myosotis-Library" # the base hostname & protocol for your site, e.g. http://example.com

title: Myosotis Library
author: 
    name: Acan
    email: xie.zeyu20@gmail.com
    github: https://github.com/zeyu-xie
description: >
    Welcome to Myosotis Library! 
lang: en
copyright: 
    label: ©️
    identity: Acan
    content: All rights reserved.

# Theme-Specific Settings

date_format: "%b %-d, %Y"

show_excerpts: false
hide_date: true